### ISSUE TITLE
Unable to run in exclusive wayland, a TTY or over SSH

### ISSUE THREAD

**Issue by prurigro** [cxreiff/ttysvr#22]
Running ttysvr without DISPLAY, WAYLAND_DISPLAY or WAYLAND_SOCKET set causes a panic with the following winit error: "neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set."

If you set the WAYLAND_DISPLAY in a wayland session,  you get a different panic with the following winit error: "DISPLAY is not set; note: enable the `winit/wayland` feature to support Wayland". It seems like wayland support would be possible, but the default build doesn't include it. Setting DISPLAY does allow it to run in wayland.

Setting DISPLAY in a TTY or over SSH to bypass the initial error results in:

```
Authorization required, but no authorization protocol specified

thread 'main' panicked at /home/prurigro/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.14.1/src/lib.rs:132:14:
Failed to build event loop: NotSupported(NotSupportedError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it seems like some sort of graphical system is required despite this being a terminal application.

**Comment by shurizzle** [comment]
#20 fixex the wayland panic (the `winit/wayland` feature one)

**Comment by cxreiff** [comment]
I've investigated getting this to work over SSH in the past, and currently bevy does not make it easy. `bevy_winit` and `bevy_render` are structured in a way that assumes that if a user does not want a winit window, they do not want the bevy render pipeline at all (WinitPlugin panics if there is no windowing system, removing WinitPlugin causes a panic if RenderPlugin is left to initialize normally). I do plan on attempting a bevy PR to fix it when I have the time to deep dive on bevy_render's code.

**Comment by cxreiff** [comment]
Scratch all of that, I was making a very silly mistake and was testing with a linux box that had no GPU. Disabling `WinitPlugin` actually works great here, I ran it with this change from an iOS SSH client and it worked perfectly. Closing, please reopen if you run into the same problem with the latest release!
